version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: "auto"
    labels:
      - "dependencies"
    reviewers:
      - "DoubledDoge"
    assignees:
      - "DoubledDoge"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "DoubledDoge"
    assignees:
      - "DoubledDoge"
