version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: "auto"
    labels:
      - "dependencies"
      - "npm"
    reviewers:
      - "Dihan Britz"
    assignees:
      - "Dihan Britz"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    update-type: "security"
    labels:
      - "security"
      - "dependencies"
    reviewers:
      - "Dihan Britz"
    assignees:
      - "DihanBritz"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "Dihan Britz"
    assignees:
      - "DihanBritz"
