name: CI/CD

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

# Allow concurrent CI runs for different PRs, but cancel in-progress runs for the same PR
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    ci:
        name: Continuous Integration
        runs-on: ubuntu-latest
        permissions:
            contents: read
            actions: write
            pull-requests: write
            security-events: write

        steps:
            - name: Checkout
              uses: actions/checkout@v5
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v5
              with:
                  node-version: '20'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Security audit
              run: npm run security-audit
              continue-on-error: true # Don't fail CI on audit warnings

            - name: Lint code
              run: npm run lint:check

            - name: Build application
              env:
                  VITE_EMAILJS_PUBLIC_KEY: ${{ secrets.EMAILJS_PUBLIC_KEY }}
                  VITE_EMAILJS_TEMPLATE_ID: ${{ secrets.EMAILJS_TEMPLATE_ID }}
                  VITE_EMAILJS_SERVICE_ID: ${{ secrets.EMAILJS_SERVICE_ID }}
              run: npm run build

            - name: Check build output
              run: |
                  echo "Build completed successfully!"
                  echo "Checking if critical files exist..."
                  test -f dist/index.html && echo "✅ index.html found" || echo "❌ index.html missing"
                  test -d dist/assets && echo "✅ assets directory found" || echo "❌ assets directory missing"
                  echo "Build size:"
                  du -sh dist/

            - name: Cache build artifacts
              uses: actions/cache@v4
              with:
                  path: |
                      dist
                      node_modules/.vite
                  key: ${{ runner.os }}-build-${{ hashFiles('package-lock.json') }}-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ hashFiles('package-lock.json') }}-
                      ${{ runner.os }}-build-

            - name: Upload build artifacts (for PRs)
              if: github.event_name == 'pull_request'
              uses: actions/upload-artifact@v4
              with:
                  name: build-artifacts-pr-${{ github.event.number }}
                  path: dist/
                  retention-days: 7
